# Site settings
title: Tara Sullivan
SEOTitle: Tara Sullivan
header-img: img/home-bg.jpg
email: tasulliv@ucsd.edu
description: "Ph.D. Candidate in Economics at University of California, San Diego"
keyword: ""
url: "https://tara-sullivan.github.io/" 

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username:    tara-sullivan
linkedin_username:  tara-sullivan-econ

# Uncomment the line below if you use this theme as a GitHub Page's remote theme.
remote_theme:  tara-sullivan/huxpro.github.io 
# 
# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: PT

# Gems
plugins: 
  - jekyll-paginate
  # - jekyll-pdf-embed

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM  # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Netease settings
netease_comment: false

# Google Analytics
# ga_track_id: 'UA-xxxxxx-xx' 

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Ph.D. Candidate in Economics at UCSD"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: false                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# # Friends
# friends: [
#     {
#     #     title: "Su",
#     #     href: "http://su.gallery/"
#     # },{
# ]
